import type {
  DefenseCardCatalog,
  DefensePossessionSetup,
  DefenseIntent,
  OpponentPlanCatalog,
} from "../core/index.ts";
import { PROTOTYPE_SETUP } from "./prototypePossession.ts";

export const PROTOTYPE_DEFENSE_CARDS = {
  pressure: {
    id: "pressure",
    name: "Pressure",
    kind: "pressure",
    timeCost: 2,
    targetMode: "ballHandler",
    risk: "Agresywna presja może ułatwić minięcie przy wejściu.",
    effects: {
      screen: {
        advantageDelta: 0,
        contestDelta: 1,
        turnoverPressureDelta: 1,
        extraClockCost: 1,
        exposure: "none",
        assignmentChange: "none",
        explanation: "Presja zabiera dodatkowy czas, ale nie neutralizuje zasłony.",
      },
      drive: {
        advantageDelta: 1,
        contestDelta: 0,
        turnoverPressureDelta: 1,
        extraClockCost: 1,
        exposure: "none",
        assignmentChange: "none",
        explanation: "Presja zużywa czas, lecz agresywne ustawienie ułatwia minięcie.",
      },
      pass: {
        advantageDelta: 0,
        contestDelta: 1,
        turnoverPressureDelta: 1,
        extraClockCost: 1,
        exposure: "none",
        assignmentChange: "none",
        explanation: "Presja skraca zegar i utrudnia bezpieczne podanie.",
      },
      shoot: {
        advantageDelta: 0,
        contestDelta: 5,
        turnoverPressureDelta: 1,
        extraClockCost: 1,
        exposure: "none",
        assignmentChange: "none",
        explanation: "Presja skraca czas i podnosi contest rzutu.",
      },
    },
  },
  switch: {
    id: "switch",
    name: "Switch",
    kind: "switch",
    timeCost: 1,
    targetMode: "actionTarget",
    risk: "Zmiana krycia może stworzyć niekorzystne dopasowanie.",
    effects: {
      screen: {
        advantageDelta: -1,
        contestDelta: 5,
        turnoverPressureDelta: 0,
        extraClockCost: 0,
        exposure: "none",
        assignmentChange: "switchScreenAssignments",
        explanation: "Zmiana krycia neutralizuje zasłonę kosztem nowego dopasowania.",
      },
    },
  },
  goUnder: {
    id: "goUnder",
    name: "Go Under",
    kind: "goUnder",
    timeCost: 1,
    targetMode: "actionTarget",
    risk: "Przejście pod zasłoną zostawia miejsce do rzutu z obwodu.",
    effects: {
      screen: {
        advantageDelta: -1,
        contestDelta: -8,
        turnoverPressureDelta: 0,
        extraClockCost: 0,
        exposure: "none",
        assignmentChange: "none",
        explanation: "Obrona odcina wejście, ale oddaje przestrzeń do rzutu.",
      },
    },
  },
  helpDefense: {
    id: "helpDefense",
    name: "Help Defense",
    kind: "helpDefense",
    timeCost: 2,
    targetMode: "actionActor",
    risk: "Pomoc zostawia partnera atakującego bez pełnego krycia.",
    effects: {
      drive: {
        advantageDelta: -2,
        contestDelta: 10,
        turnoverPressureDelta: 0,
        extraClockCost: 0,
        exposure: "actionTarget",
        assignmentChange: "none",
        explanation: "Pomoc zatrzymuje wejście, ale odsłania opcję podania.",
      },
    },
  },
  doubleTeam: {
    id: "doubleTeam",
    name: "Double Team",
    kind: "doubleTeam",
    timeCost: 3,
    targetMode: "ballHandler",
    risk: "Podwojenie ma 30% bazowej szansy straty, ale otwiera partnera.",
    effects: {
      screen: {
        advantageDelta: -1,
        contestDelta: 1,
        turnoverPressureDelta: 2,
        extraClockCost: 0,
        exposure: "actionActor",
        assignmentChange: "none",
        explanation: "Podwojenie atakuje piłkę, ale odsłania stawiającego zasłonę.",
      },
      drive: {
        advantageDelta: -1,
        contestDelta: 2,
        turnoverPressureDelta: 2,
        extraClockCost: 0,
        exposure: "actionTarget",
        assignmentChange: "none",
        explanation: "Podwojenie utrudnia wejście, ale otwiera partnera.",
      },
      pass: {
        advantageDelta: 1,
        contestDelta: -2,
        turnoverPressureDelta: 2,
        extraClockCost: 0,
        exposure: "actionTarget",
        assignmentChange: "none",
        explanation: "Podwojenie grozi stratą, lecz udane podanie tworzy otwartą pozycję.",
      },
      shoot: {
        advantageDelta: 0,
        contestDelta: 6,
        turnoverPressureDelta: 2,
        extraClockCost: 0,
        exposure: "none",
        assignmentChange: "none",
        explanation: "Podwojenie mocno kontestuje rzut, ale jest kosztowne.",
      },
    },
  },
} as const satisfies DefenseCardCatalog;

export const PROTOTYPE_OPPONENT_PLANS = {
  pickAndRoll: {
    id: "pickAndRoll",
    name: "Pick & Roll",
    description: "Zasłona dla rozgrywającego i wejście w paint.",
    steps: [
      {
        id: "pnr-screen",
        name: "Screen",
        kind: "screen",
        actorId: "opponent-c",
        targetId: "opponent-pg",
        baseAdvantageDelta: 1,
      },
      {
        id: "pnr-drive",
        name: "Drive",
        kind: "drive",
        actorId: "opponent-pg",
        targetId: "opponent-c",
        baseAdvantageDelta: 1,
      },
      {
        id: "pnr-shot",
        name: "Paint Finish",
        kind: "shoot",
        actorId: "opponent-pg",
        baseAdvantageDelta: 0,
      },
    ],
  },
  driveAndKick: {
    id: "driveAndKick",
    name: "Drive & Kick",
    description: "Wejście skrzydłowego i odegranie na obwód.",
    steps: [
      {
        id: "dak-drive",
        name: "Drive",
        kind: "drive",
        actorId: "opponent-pg",
        targetId: "opponent-wing",
        baseAdvantageDelta: 1,
      },
      {
        id: "dak-pass",
        name: "Kick Out",
        kind: "pass",
        actorId: "opponent-pg",
        targetId: "opponent-wing",
        baseAdvantageDelta: 0,
      },
      {
        id: "dak-shot",
        name: "Corner Shot",
        kind: "shoot",
        actorId: "opponent-wing",
        baseAdvantageDelta: 0,
      },
    ],
  },
  quickThree: {
    id: "quickThree",
    name: "Quick Three",
    description: "Szybkie podanie i zasłona pod rzut z obwodu.",
    steps: [
      {
        id: "q3-pass",
        name: "Swing Pass",
        kind: "pass",
        actorId: "opponent-pg",
        targetId: "opponent-wing",
        baseAdvantageDelta: 0,
      },
      {
        id: "q3-screen",
        name: "Off-ball Screen",
        kind: "screen",
        actorId: "opponent-c",
        targetId: "opponent-wing",
        baseAdvantageDelta: 1,
      },
      {
        id: "q3-shot",
        name: "Quick Three",
        kind: "shoot",
        actorId: "opponent-wing",
        baseAdvantageDelta: 0,
      },
    ],
  },
} as const satisfies OpponentPlanCatalog;

export const PROTOTYPE_OPPONENT_DEFENSE_INTENTS = [
  {
    id: "pressure-and-help",
    name: "Pressure & Help",
    description: "Presja na piłkę i szybka pomoc po wejściu.",
    onBallPressure: 6,
    matchupContest: 12,
    helpOnDrive: true,
  },
  {
    id: "protect-paint",
    name: "Protect Paint",
    description: "Mniejsza presja na obwodzie, mocna pomoc przy wejściu.",
    onBallPressure: 2,
    matchupContest: 10,
    helpOnDrive: true,
  },
  {
    id: "deny-perimeter",
    name: "Deny Perimeter",
    description: "Agresywne krycie obwodu bez automatycznej pomocy w paint.",
    onBallPressure: 8,
    matchupContest: 16,
    helpOnDrive: false,
  },
] as const satisfies readonly DefenseIntent[];

export const PROTOTYPE_DEFENSE_SETUP: DefensePossessionSetup = {
  shotClock: 14,
  ballHandlerId: "opponent-pg",
  hand: ["pressure", "switch", "goUnder", "helpDefense", "doubleTeam"],
  players: [
    {
      id: "opponent-pg",
      name: "Razor",
      side: "offense",
      zone: "topPerimeter",
      shooting: 72,
    },
    {
      id: "opponent-wing",
      name: "Flash",
      side: "offense",
      zone: "leftPerimeter",
      shooting: 78,
    },
    {
      id: "opponent-c",
      name: "Brick",
      side: "offense",
      zone: "rightPerimeter",
      shooting: 48,
    },
    {
      id: "player-pg",
      name: "Nova",
      side: "defense",
      zone: "topPerimeter",
      shooting: 60,
    },
    {
      id: "player-wing",
      name: "Echo",
      side: "defense",
      zone: "leftPerimeter",
      shooting: 76,
    },
    {
      id: "player-c",
      name: "Atlas",
      side: "defense",
      zone: "rightPerimeter",
      shooting: 44,
    },
  ],
  assignments: [
    { defenderId: "player-pg", offenderId: "opponent-pg" },
    { defenderId: "player-wing", offenderId: "opponent-wing" },
    { defenderId: "player-c", offenderId: "opponent-c" },
  ],
  shotQuality: PROTOTYPE_SETUP.rules.shotQuality,
};
